# Generated by Django 3.1.3 on 2020-11-18 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201118_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='file',
            new_name='image',
        ),
    ]
